[env]
MISE_SHORTHAND = true              # Allow shorthand like `node 18` instead of `node@18`
MISE_CONFIG_DIR = "~/.config/mise" # Override default config directory (optional)

[settings]
legacy_version_file = true         # Support idiomatic files like .nvmrc, .python-version
auto_install         = true        # Automatically install missing tools on use
experimental         = true        # Enable fuzzy version matching (e.g., node 18 → latest 18.x)
jobs                 = 8           # Use 8 cores for parallel installs (use "max" for auto-detect)
verbose              = false       # Keep output minimal (less noise in terminal)
paranoid             = true        # Warn on unknown or misconfigured versions/tools
not_found_auto_install = true      # Install tools when a matching command is missing
always_keep_download = false       # Delete install files after use to save space
trusted_config_paths = ["~"]       # Only trust user-level config files (safer for shared codebases)
plugin_autoupdate_last_check_duration = "1d"  # Check for plugin updates every 1 day
default_tool_versions_filename = ".tool-versions"

idiomatic_version_file_enable_tools = [  # Explicitly allow idiomatic version files per tool
  "node",    # Supports `.nvmrc`
  "python",  # Supports `.python-version`
  "ruby",    # Supports `.ruby-version`
  "java",    # e.g., `.java-version` (jenv-style)
  "rust",    # Supports `rust-toolchain`
  "php",
  "elixir",
  "erlang",
  "go",
  "lua"
]