# Yarn registry and network settings
npmRegistryServer: "https://registry.npmjs.org"
networkConcurrency: 16 # Increases the number of concurrent network requests for faster installs
httpTimeout: 30000 # 30-second timeout for network requests

# Caching for improved performance
cacheFolder: "~/.yarn-cache" # Specifies cache folder for quicker re-installs
preferOffline: true # Use local cache whenever possible

# Dependency installation settings
save-exact: true # Lock exact versions to avoid version drift
enableGlobalCache: true # Use a single global cache for all projects
nodeLinker: "node-modules" # Uses node_modules for installs, faster and more compatible with legacy tooling

# Security and Auth
strictSsl: true # Enforce SSL for secure connections

# Logging and user feedback
enableProgressBars: false # Disable progress bars for cleaner logs, helpful in CI environments
logLevel: "error" # Display only errors to reduce log noise

# Optional Settings
defaultAudit: true # Disables audit checks for faster installs, enable in production if necessary
pnpFallbackMode: "none" # Improves performance by reducing work on dependency conflicts
checksumBehavior: "update" # Automatically updates checksums, useful for local development

# Auto-accept prompts
preferInteractive: false # Disables interactive prompts, useful for automation and CI/CD
