#!/usr/bin/env bash
# Optional: install a git pre-commit hook in this dotfiles repo that runs the
# Cursor ↔ Gemini drift detector against the staged index. Idempotent.
#
# Usage:
#   ./ai/gemini-content-team/hooks/install-pre-commit.sh
#
# Uninstall: delete `.git/hooks/pre-commit` (or restore the previous one from
# the .bak this script writes when it overwrites an existing hook).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
HOOK_DIR="$ROOT/.git/hooks"
HOOK_PATH="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"

if [[ -f "$HOOK_PATH" ]] && ! grep -q 'verify-gemini-manifest.sh' "$HOOK_PATH" 2>/dev/null; then
  cp "$HOOK_PATH" "$HOOK_PATH.bak.$(date +%s)"
  echo "Existing pre-commit backed up to $HOOK_PATH.bak.<ts>"
fi

cat >"$HOOK_PATH" <<'PRECOMMIT'
#!/usr/bin/env bash
# dotfiles pre-commit: Cursor ↔ Gemini content-pack drift detector.
# Generated by ai/gemini-content-team/hooks/install-pre-commit.sh
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
SCRIPT="$ROOT/ai/gemini-content-team/hooks/verify-gemini-manifest.sh"
[[ -x "$SCRIPT" ]] || { echo "drift detector missing: $SCRIPT" >&2; exit 1; }
"$SCRIPT" --staged
PRECOMMIT

chmod +x "$HOOK_PATH"
echo "Installed pre-commit hook at $HOOK_PATH"
echo "It runs: ./ai/gemini-content-team/hooks/verify-gemini-manifest.sh --staged"
